# Compile-time Options

## `TE_FLOAT` {-}

`double` is the default data type used for the parser's variable types, parameters, and return types.
For embedded environments that require `float`, compile with `TE_FLOAT` defined to use `float` instead.

When using this option, it is recommended to use the helper typedef `te_type`.
This will map to either `float` or `double` (depending on whether `TE_FLOAT` is defined).
By defining your functions and variables with `te_type`,
you won't need to replace `double` and `float` if needing to change this compiler flag.

## `TE_POW_FROM_RIGHT` {-}

By default, *TinyExpr++* does exponentiation from left to right. For example:

`a^b^c == (a^b)^c` and `-a^b == (-a)^b`

This is by design; it's the way that spreadsheets do it
(e.g., *LibreOffice Calc*, *Excel*, *Google Sheets*).

If you would rather have exponentiation work from right to left, you need to
define `TE_POW_FROM_RIGHT`\index{compiling!options} when compiling. With `TE_POW_FROM_RIGHT` defined, the
behavior is:

`a^b^c == a^(b^c)` and `-a^b == -(a^b)`

That will match how many scripting languages do it (e.g., Python, Ruby).

Note that symbols can be defined by passing them to your compiler's
command line (or in a Cmake configuration) as such: `-DTE_POW_FROM_RIGHT`
