--- 
title: "TinyExpr++ Reference Manual"
author: Blake Madden
date: 2023
documentclass: book
site: bookdown::bookdown_site
lot: yes
biblio-title: References
bibliography: cites.bib
biblio-style: mla
link-citations: true
nocite: '@*'
csl: modern-language-association.csl
---

```{r, include=FALSE}
library(DiagrammeR)
library(webshot)
# Run this if diagrams do not appear in PDF
# or you get an error about HTML in your PDF.
# webshot::install_phantomjs()
```

# Overview

This is the reference manual for *TinyExpr++*, the C++ version of the *TinyExpr* [@TinyExpr] formula parsing library. (This manual includes documentation from *TinyExpr* by Lewis Van Winkle.)

*TinyExpr++* is a small parser and evaluation library for solving math expressions from C++.
It's open-source, free, easy-to-use, and self-contained in a single source and header file pair.

## Features

- C++17 with no dependencies.
- Single source file and header file.
- Simple and fast.
- Implements standard operator precedence.
- Implements logical and comparison operators.
- Exposes standard C math functions (`sin`, `sqrt`, `ln`, etc.), as well as some *Excel*-like functions (e.g., `AVERAGE()` and `IF()`).
- Can add custom functions and variables easily.
- Can bind constants at eval-time.
- Supports variadic functions (taking between 1-7 arguments).
- Case insensitive.
- Supports non-US formulas (e.g., `POW(2,2; 2)` instead of `POW(2.2, 2)`).
- Supports C and C++ style comments within math expressions.
- Released under the zlib license - free for nearly any use.
- Easy to use and integrate with your code.
- Thread-safe; parser is in a self-contained object.
