name: doxygen
on: [push,pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: doxygen-test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: 'true'

      - name: install doxygen
        run: |
             sudo apt install doxygen

      - name: run doxygen
        run: |
             cd docs
             doxygen Doxyfile
